title: Science Ouverte
description: Ouvrir les publications, partager les données
footer_text: université de Rennes 1
header_feature_image: ../uploads/pages.png
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logo_rennes1.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: La science ouverte à Rennes 1
    siteurl: https://scienceouverte.univ-rennes1.fr/enjeux-de-lopen-access
  - name: Focus
    siteurl: https://focus.univ-rennes1.fr
